server:
  port: 8888
spring:
  application:
    name: config-server
#  profiles:
#    active: native
  config:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/robot-advent/springcloud
          username: robot-advent
          password: Qtvb.520
          default-label: master
          search-paths: /
#        svn:
#          uri:
#          default-label:
#          password:
#          username:
#          search-paths:
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/